# Dragon Real Estate -Price Predictor

In [1]:
import pandas as pd

In [2]:
housing = pd.read_csv("datasets1.csv")

In [3]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       501 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [5]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  501.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284116   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.704200   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885000   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208000   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.625000   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [6]:
# %matplotlib inline
# import matplotlib.pyplot as plt
# housing.hist(bins = 50 ,figsize=(20,15))

# Train-Test Splitting

In [7]:
# import numpy as np
# def split_train_test(data,test_ratio):
#     np.random.seed(42)
#     shuffled = np.random.permutation(len(data))
#     test_set_size = int(len(data)*test_ratio)
#     test_indices = shuffled[:test_set_size]
#     train_indices = shuffled[test_set_size:]
#     return data.iloc[train_indices],data.iloc[test_indices]

In [8]:
# train_set,test_set = split_train_test(housing,0.2)

In [9]:
# len(train_set)

In [10]:
# len(test_set)

In [11]:
from sklearn.model_selection import train_test_split
train_set ,test_set = train_test_split(housing,test_size=0.2,random_state = 42)

In [12]:
len(train_set)


404

In [13]:
len(test_set)

102

In [14]:
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=42)
for train_index,test_index in split.split(housing,housing['CHAS']):
    strat_train_set = housing.loc[train_index]
    strat_test_set = housing.loc[test_index]

In [15]:
housing = strat_train_set.copy()

In [16]:
# Looking for Correlation

In [17]:
corr_matrix = housing.corr()
corr_matrix['MEDV'].sort_values(ascending = False)

MEDV       1.000000
RM         0.678248
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [18]:
# from pandas.plotting import scatter_matrix

# attributes =["MEDV","RM","ZN","LSTAT"]
# scatter_matrix(housing[attributes],figsize = (12,8))

In [19]:
# housing.plot(kind = 'scatter',x='RM',y='MEDV',alpha=1)

# Trying out attribute combinations

In [20]:
housing['TAXRM']=housing['TAX']/housing['RM']

In [21]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
254  0.04819  80.0   3.64     0  0.392  6.108  32.0  9.2203    1  315   
348  0.01501  80.0   2.01     0  0.435  6.635  29.7  8.3440    4  280   
476  4.87141   0.0  18.10     0  0.614  6.484  93.6  2.3053   24  666   
321  0.18159   0.0   7.38     0  0.493  6.376  54.3  4.5404    5  287   
326  0.30347   0.0   7.38     0  0.493  6.312  28.9  5.4159    5  287   

     PTRATIO       B  LSTAT  MEDV       TAXRM  
254     16.4  392.89   6.57  21.9   51.571709  
348     17.0  390.94   5.99  24.5   42.200452  
476     20.2  396.21  18.68  16.7  102.714374  
321     19.6  396.90   6.87  23.1   45.012547  
326     19.6  396.90   6.15  23.0   45.468948

In [22]:
housing = strat_train_set.drop("MEDV",axis=1)
housing_labels = strat_train_set["MEDV"].copy()

# Missing Attributes

In [23]:
# To take care of missing attributes, you have three option:
#     1.get rid of the missing data points
#     2.get rid of the whole attribute
#     3.set the value to some value (0,mean or median)

In [24]:
a = housing.dropna(subset=["RM"]) #option1
a.shape

(400, 13)

In [25]:
housing.drop("RM",axis=1) #option2

CRIM    ZN  INDUS  CHAS    NOX   AGE     DIS  RAD  TAX  PTRATIO  \
254  0.04819  80.0   3.64     0  0.392  32.0  9.2203    1  315     16.4   
348  0.01501  80.0   2.01     0  0.435  29.7  8.3440    4  280     17.0   
476  4.87141   0.0  18.10     0  0.614  93.6  2.3053   24  666     20.2   
321  0.18159   0.0   7.38     0  0.493  54.3  4.5404    5  287     19.6   
326  0.30347   0.0   7.38     0  0.493  28.9  5.4159    5  287     19.6   
..       ...   ...    ...   ...    ...   ...     ...  ...  ...      ...   
155  3.53501   0.0  19.58     1  0.871  82.6  1.7455    5  403     14.7   
423  7.05042   0.0  18.10     0  0.614  85.1  2.0218   24  666     20.2   
98   0.08187   0.0   2.89     0  0.445  36.9  3.4952    2  276     18.0   
455  4.75237   0.0  18.10     0  0.713  86.5  2.4358   24  666     20.2   
216  0.04560   0.0  13.89     1  0.550  56.0  3.1121    5  276     16.4   

          B  LSTAT  
254  392.89   6.57  
348  390.94   5.99  
476  396.21  18.68  
321  396.90   6.87  
326  396.90   6.15  
..      ...    ...  
155   88.01  15.02  
423    2.52  23.29  
98   393.53   3.57  
455   50.92  18.13  
216  392.80  13.51  

[404 rows x 12 columns]

In [26]:

median =  housing["RM"].median() #option 3
housing["RM"].fillna(median)

254    6.108
348    6.635
476    6.484
321    6.376
326    6.312
       ...  
155    6.152
423    6.103
98     7.820
455    6.525
216    5.888
Name: RM, Length: 404, dtype: float64

In [27]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy= 'median')
imputer.fit(housing)

SimpleImputer(strategy='median')

In [28]:
imputer.statistics_

array([2.86735e-01, 0.00000e+00, 9.90000e+00, 0.00000e+00, 5.38000e-01,
       6.21000e+00, 7.82000e+01, 3.12220e+00, 5.00000e+00, 3.37000e+02,
       1.90000e+01, 3.90955e+02, 1.15700e+01])

In [29]:
X= imputer.transform(housing)

In [30]:
housing_tr = pd.DataFrame(X)

In [31]:
housing_tr.describe()

0           1           2           3           4           5   \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.278824   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.710678   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.879750   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.210000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630000   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

               6           7           8           9           10          11  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

               12  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

# Scikit-learn Design

Primarily,three types of objects
1. Estimators -It estimates some parameter based on a dataset. eg. imputer. It has a fit method and trabsform method.Fit method - Fits the dataset and calculates internal parameters

2. Transformers - transforn method takes input and returns output based on the learning from() .It also has a conveniec=nce function called fit_transform() which fit and then transforms.

3. Predictors - LinearRegression Model is an example of predictor.fit() and predit() are two common functions . Its also give score() function which will evalute the predictions.

## Feature Scaling

Primarily , two types of feature scaling Methods:
1. Min-max scaling (Normalization)
  (value-min)/(max-min)
  Sklearn provide a class called MinMaxScaler for this
  
2. Standardization
   (value- mean)/std
   Sklearn provide a class called Standard Scaler for this

## Creating Pipeline

In [32]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_pipeline = Pipeline([
    ('imputer',SimpleImputer(strategy="median")),
    ('std_scalar',StandardScaler()),
])

In [33]:
housing_num_tr = my_pipeline.fit_transform(housing)

In [34]:
housing_num_tr.shape

(404, 13)

## Selecting a desired model for Dragon Estates

In [35]:
# from sklearn.linear_model import LinearRegression
# model = LinearRegression()
# from sklearn.tree import DecisionTreeRegressor
# model = DecisionTreeRegressor()

from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(housing_num_tr,housing_labels)

RandomForestRegressor()

In [36]:
some_data = housing.iloc[:5]

In [37]:
some_labels = housing_labels.iloc[:5]

In [38]:
prepared_data = my_pipeline.transform(some_data)

In [39]:
model.predict(prepared_data)

array([22.543, 25.408, 16.267, 23.367, 23.647])

In [40]:
list(some_labels)

[21.9, 24.5, 16.7, 23.1, 23.0]

## Evaluating the model

In [41]:
import numpy as np
from sklearn.metrics import mean_squared_error
housing_predictions = model.predict(housing_num_tr)
mse = mean_squared_error(housing_labels,housing_predictions)
rms = np.sqrt(mse)

In [42]:
rms

1.226169130921081

## Using Better Evaluation technique - cross Validation

In [43]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model,housing_num_tr,housing_labels,scoring = "neg_mean_squared_error",cv=10)
rmse_scores = np.sqrt(-scores)

In [44]:
rmse_scores

array([2.7174367 , 2.66699997, 4.56612965, 2.66812311, 3.77129721,
       2.79630243, 4.50614138, 3.32490779, 3.3458581 , 3.19106282])

In [45]:
def print_scores(scores):
    print("Scores:", scores)
    print("Mean:",scores.mean())
    print("Standard deviation", scores.std())

In [46]:
print_scores(rmse_scores)

Scores: [2.7174367  2.66699997 4.56612965 2.66812311 3.77129721 2.79630243
 4.50614138 3.32490779 3.3458581  3.19106282]
Mean: 3.3554259162986773
Standard deviation 0.6824149325968643


## Saving The model

In [47]:
from joblib import dump , load
dump(model,'Dargon.joblib')

['Dargon.joblib']

# Testing The model On Test Data

In [49]:
x_test = strat_test_set.drop("MEDV",axis = 1)
y_test = strat_test_set["MEDV"].copy()
x_test_prepared = my_pipeline.transform(x_test)
final_prediction  = model.predict(x_test_prepared)
final_mse = mean_squared_error (y_test,final_prediction)
final_rmse = np.sqrt(final_mse) 

In [50]:
final_rmse

2.7835723573543842

In [51]:
prepared_data

array([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
        -0.24066617, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
        -0.97491834,  0.41164221, -0.86091034],
       [-0.44352175,  3.12628155, -1.35893781, -0.27288841, -1.0542567 ,
         0.50179906, -1.3938808 ,  2.19312325, -0.65766683, -0.78557904,
        -0.69277865,  0.39131918, -0.94116739],
       [ 0.15682292, -0.4898311 ,  0.98336806, -0.27288841,  0.47919371,
         0.28906235,  0.87020968, -0.68730678,  1.63579367,  1.50571521,
         0.81196637,  0.44624347,  0.81480158],
       [-0.42292925, -0.4898311 , -0.57719868, -0.27288841, -0.5573845 ,
         0.13690628, -0.52225911,  0.37882487, -0.5429938 , -0.74402708,
         0.52982668,  0.45343469, -0.81939807],
       [-0.40786253, -0.4898311 , -0.57719868, -0.27288841, -0.5573845 ,
         0.04673973, -1.42222622,  0.79643404, -0.5429938 , -0.74402708,
         0.52982668,  0.45343469, -0.91902752]])